allowBuilds:
  '@reown/appkit': set this to true or false
  '@stellar/stellar-sdk': set this to true or false
  blake-hash: set this to true or false
  bufferutil: set this to true or false
  core-js: set this to true or false
  cypress: set this to true or false
  protobufjs: set this to true or false
  secp256k1: set this to true or false
  sharp: set this to true or false
  tiny-secp256k1: set this to true or false
  unrs-resolver: set this to true or false
  usb: set this to true or false
  utf-8-validate: set this to true or false
minimumReleaseAgeExclude:
  - '@posthog/core@1.44.0'
  - '@posthog/types@1.397.1'
  - postcss@8.5.21
  - posthog-js@1.405.3
  - posthog-node@5.46.0
