/* tslint:disable */
/* eslint-disable */
/**
 * Stellarcarbon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MemoType = {
    Text: 'text',
    Hash: 'hash'
} as const;
export type MemoType = typeof MemoType[keyof typeof MemoType];


export function MemoTypeFromJSON(json: any): MemoType {
    return MemoTypeFromJSONTyped(json, false);
}

export function MemoTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemoType {
    return json as MemoType;
}

export function MemoTypeToJSON(value?: MemoType | null): any {
    return value as any;
}

