/* tslint:disable */
/* eslint-disable */
/**
 * Stellarcarbon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PaymentAsset = {
    Xlm: 'XLM',
    Usdc: 'USDC',
    Any: 'any'
} as const;
export type PaymentAsset = typeof PaymentAsset[keyof typeof PaymentAsset];


export function PaymentAssetFromJSON(json: any): PaymentAsset {
    return PaymentAssetFromJSONTyped(json, false);
}

export function PaymentAssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentAsset {
    return json as PaymentAsset;
}

export function PaymentAssetToJSON(value?: PaymentAsset | null): any {
    return value as any;
}

