/* tslint:disable */
/* eslint-disable */
/**
 * Stellarcarbon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SinkingResponse
 */
export interface SinkingResponse {
    /**
     * 
     * @type {string}
     * @memberof SinkingResponse
     */
    funder: string;
    /**
     * 
     * @type {string}
     * @memberof SinkingResponse
     */
    recipient: string;
    /**
     * 
     * @type {string}
     * @memberof SinkingResponse
     */
    carbonAmount: string;
    /**
     * 
     * @type {string}
     * @memberof SinkingResponse
     */
    usdcAmount: string;
    /**
     * 
     * @type {number}
     * @memberof SinkingResponse
     */
    vcsProjectId: number;
    /**
     * 
     * @type {string}
     * @memberof SinkingResponse
     */
    txXdr: string;
    /**
     * 
     * @type {string}
     * @memberof SinkingResponse
     */
    txrep: string;
}

/**
 * Check if a given object implements the SinkingResponse interface.
 */
export function instanceOfSinkingResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "funder" in value;
    isInstance = isInstance && "recipient" in value;
    isInstance = isInstance && "carbonAmount" in value;
    isInstance = isInstance && "usdcAmount" in value;
    isInstance = isInstance && "vcsProjectId" in value;
    isInstance = isInstance && "txXdr" in value;
    isInstance = isInstance && "txrep" in value;

    return isInstance;
}

export function SinkingResponseFromJSON(json: any): SinkingResponse {
    return SinkingResponseFromJSONTyped(json, false);
}

export function SinkingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SinkingResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'funder': json['funder'],
        'recipient': json['recipient'],
        'carbonAmount': json['carbon_amount'],
        'usdcAmount': json['usdc_amount'],
        'vcsProjectId': json['vcs_project_id'],
        'txXdr': json['tx_xdr'],
        'txrep': json['txrep'],
    };
}

export function SinkingResponseToJSON(value?: SinkingResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'funder': value.funder,
        'recipient': value.recipient,
        'carbon_amount': value.carbonAmount,
        'usdc_amount': value.usdcAmount,
        'vcs_project_id': value.vcsProjectId,
        'tx_xdr': value.txXdr,
        'txrep': value.txrep,
    };
}

