/* tslint:disable */
/* eslint-disable */
/**
 * Stellarcarbon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CarbonAmount
 */
export interface CarbonAmount {
}

/**
 * Check if a given object implements the CarbonAmount interface.
 */
export function instanceOfCarbonAmount(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CarbonAmountFromJSON(json: any): CarbonAmount {
    return CarbonAmountFromJSONTyped(json, false);
}

export function CarbonAmountFromJSONTyped(json: any, ignoreDiscriminator: boolean): CarbonAmount {
    return json;
}

export function CarbonAmountToJSON(value?: CarbonAmount | null): any {
    return value;
}

