/* tslint:disable */
/* eslint-disable */
/**
 * Stellarcarbon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuoteResponse
 */
export interface QuoteResponse {
    /**
     * 
     * @type {string}
     * @memberof QuoteResponse
     */
    carbonAmount: string;
    /**
     * 
     * @type {string}
     * @memberof QuoteResponse
     */
    totalCost: string;
    /**
     * 
     * @type {string}
     * @memberof QuoteResponse
     */
    averagePrice: string;
}

/**
 * Check if a given object implements the QuoteResponse interface.
 */
export function instanceOfQuoteResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "carbonAmount" in value;
    isInstance = isInstance && "totalCost" in value;
    isInstance = isInstance && "averagePrice" in value;

    return isInstance;
}

export function QuoteResponseFromJSON(json: any): QuoteResponse {
    return QuoteResponseFromJSONTyped(json, false);
}

export function QuoteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuoteResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'carbonAmount': json['carbon_amount'],
        'totalCost': json['total_cost'],
        'averagePrice': json['average_price'],
    };
}

export function QuoteResponseToJSON(value?: QuoteResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'carbon_amount': value.carbonAmount,
        'total_cost': value.totalCost,
        'average_price': value.averagePrice,
    };
}

